name: Sprint Labeler

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add sprint label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            const year = now.getUTCFullYear();
            const monthNames = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
            const colors = {
              Jan: "1f77b4",
              Feb: "ff7f0e",
              Mar: "2ca02c",
              Apr: "d62728",
              May: "9467bd",
              Jun: "8c564b",
              Jul: "e377c2",
              Aug: "7f7f7f",
              Sep: "bcbd22",
              Oct: "17becf",
              Nov: "ff33cc",
              Dec: "33cc33"
            };

            const month = monthNames[now.getUTCMonth()];
            const labelName = `SRE-Sprint-${year}-${month}`;
            const labelColor = colors[month] || "0e8a16";

            // remove any existing sprint labels
            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            for (const l of currentLabels) {
              if (l.name.startsWith("SRE-Sprint-")) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: l.name,
                }).catch(() => {}); // ignore if already removed
              }
            }

            // ensure label exists in repo (create if missing)
            try {
              await github.rest.issues.getLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: labelName,
              });
            } catch {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: labelName,
                color: labelColor,
                description: `Sprint label for ${month} ${year}`,
              });
            }

            // add the sprint label to the issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [labelName],
            });
