name: Auto Sprint Label

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Sprint Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            test-label
